sim:far_forward_dvcs:
  extends: .det_benchmark
  stage: simulate
  timeout: 4 hours
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores $MAX_CORES_PER_JOB sim_output/far_forward_dvcs/epic_craterlake_10x100/DVCS.1.ab.hiAcc.10x100.eicrecon.edm4eic.root
    - snakemake $SNAKEMAKE_FLAGS --cores $MAX_CORES_PER_JOB sim_output/far_forward_dvcs/epic_craterlake_5x41/DVCS.1.ab.hiAcc.5x41.eicrecon.edm4eic.root
  retry:
    max: 2
    when:
      - runner_system_failure

bench:far_forward_dvcs:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:far_forward_dvcs"]
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 far_forward_dvcs_run_locally

collect_results:far_forward_dvcs:
  extends: .det_benchmark
  stage: collect
  needs:
    - "bench:far_forward_dvcs"
  script:
    - ls -lrht
    - mv results{,_save}/ # move results directory out of the way to preserve it
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output far_forward_dvcs_run_locally
    - mv results{_save,}/
